name: First_Workflow

on:  workflow_dispatch

jobs:
  First_Job:
    runs-on: ubuntu-latest
    steps:
      - name: Step_1
        run: echo "hello!!"
      - name: Step_2
        run: echo "good bye"
